site_name: pyMkDocs

theme:
  name: material

  features:
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - files:
    - /__init__.py: vmdoc/_init_.py_b76991.txt
    - /include/vmdoc.py: vmdoc/vmdoc.py_99ab01.txt
  - Home: index.md
  - vmdoc: vmdoc/vmdocs.md
markdown_extensions:
  - codehilite:
      guess_lang: false # Ensures correct language highlighting
  - fenced_code
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
